# TODO check to see if its installed first
- name: Installing plugins
  shell: sudo -E -u logstash {{logstash_install_path}}/logstash-{{ logstash_version  }}/bin/plugin install {{ item.name }} chdir={{logstash_install_path}}/logstash-{{ logstash_version  }}
  environment:
    JAVA_HOME: "{{ logstash_java_home }}"
  with_items: logstash_plugins
  when: logstash_plugins is defined

- name: Updating plugins
  shell: sudo -E -u logstash /opt/logstash-{{ logcentral_logstash_version | default('1.5.0.rc2') }}/bin/plugin update chdir=/opt/logstash-{{ logcentral_logstash_version | default('1.5.0.rc2') }}
  environment:
    JAVA_HOME: /opt/java/java8
  when: logstash_plugins_update